version: '3.8'

services:
  db:
    container_name:  cash_db
    image: postgres:13.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:
